apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-app
  namespace: argocd
spec:
  project: argocd-control-plane

  source:
    repoURL: https://github.com/RamitTechnical/control-plane.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
